export const SHOW_CHARACTERS = "SHOW_CHARACTERS";
export const SHOW_COMICS_CHARACTER = "SHOW_COMICS_CHARACTER";
export const SHOW_COMIC = "SHOW_COMIC";
export const SEARCH_CHARACTERS_NAME = "SEARCH_CHARACTERS_NAME";